name:                hts-project
version:             0.1.0.0
github:              "aki99/hts-project"
license:             BSD3
author:              "aki99"
maintainer:          "aki99@github.com"
copyright:           "2020 aki99"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aki99/hts-project#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- containers
# Web Client
- wreq
- aeson
# Lens
- lens
- lens-aeson

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DuplicateRecordFields
    - TemplateHaskell

executables:
  hts-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hts-project

tests:
  hts-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hts-project
